name: "MQTT ClientT"
version: "latest"
slug: "mqtt_clientT"
description: "An MQTTtt client running in a pre-built Docker container."
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
host_network: true
image: "sergheislobodeaniuc/my_mqtt_app"
options:
  broker_ip: "192.168.1.222"
  broker_port: 1883
  mqtt_user: "user"
  mqtt_pass: "your_pass"
schema:
  broker_ip: str
  broker_port: port
  mqtt_user: str
  mqtt_pass: password
